=== 2DEN58/Aircraft/Aircraft/aircraftEngine.dtd
<!ELEMENT engines (engine+)>
<!ELEMENT engine (type,name,manufacturer,first_run,major_application,specification,description)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT manufacturer (#PCDATA)>
<!ELEMENT first_run (#PCDATA)>
<!ELEMENT major_application (#PCDATA)>
<!ELEMENT specification (size,weight,thrust)>
<!ELEMENT size (length,width,height,fan_diameter)>
<!ATTLIST size dimension CDATA #REQUIRED>
<!ELEMENT length (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT fan_diameter (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ATTLIST weight mass CDATA #REQUIRED>
<!ELEMENT thrust (#PCDATA)>
<!ATTLIST thrust power CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>

=== 2DEN58/Aircraft/Aircraft/aircfatEngine.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE engines SYSTEM "aircraftEngine.dtd">
<engines>
  <engine>
    <type>Turbofan</type>
    <name>GE90</name>
    <manufacturer>General Electric</manufacturer>
    <first_run>1993</first_run>
    <major_application>Boeing 777</major_application>
    <specification >
      <size dimension="m">
        <length>7.29</length>
        <width>3.87</width>
        <height>3.95</height>
        <fan_diameter>3.1</fan_diameter>
      </size>
      <weight mass="kg">7,893</weight>
      <thrust power="kN">432.8</thrust>
    </specification>
    <description>The most powerful engine in the world</description>
  </engine>

  <engine>
    <type>Turbofan</type>
    <name>Trent XWB</name>
    <manufacturer>Rolls-Royce</manufacturer>
    <first_run>2010</first_run>
    <major_application>Airbus A350</major_application>
    <specification >
      <size dimension="m">
        <length>4.97</length>
        <width>3</width>
        <height>3.05</height>
        <fan_diameter>3</fan_diameter>
      </size>
      <weight mass="kg">6,800</weight>
      <thrust power="kN">430</thrust>
    </specification>
    <description>The most efficient engine in the world</description>
  </engine>

  <engine>
    <type>Turbofan</type>
    <name>Trent 900</name>
    <manufacturer>Rolls-Royce</manufacturer>
    <first_run>2003</first_run>
    <major_application>Airbus A380</major_application>
    <specification >
      <size dimension="m">
        <length>4.55</length>
        <width>2.94</width>
        <height>2.94</height>
        <fan_diameter>2.95</fan_diameter>
      </size>
      <weight mass="kg">6,271</weight>
      <thrust power="kN">311-374</thrust>
    </specification>
    <description>The main engine of the biggest passenger airplane in the world</description>
  </engine>

  <engine>
    <type>Turbofan</type>
    <name>CF6</name>
    <manufacturer>General Electric</manufacturer>
    <first_run>1971</first_run>
    <major_application>A300, A310, A330, 747, 767, DC-10, MD-11</major_application>
    <specification >
      <size dimension="m">
        <length>4.55</length>
        <width>2.94</width>
        <height>2.94</height>
        <fan_diameter>2.95</fan_diameter>
      </size>
      <weight mass="kg">6,271</weight>
      <thrust power="kN">186</thrust>
    </specification>
    <description>One of the most succesful service engine in the world</description>
  </engine>
</engines>
